### ISSUE TITLE
The class decorators are not correctly positioned in the AST.

### ISSUE THREAD

**Issue by bstefanescu** [meriyah/meriyah#105]
The class decorators array is put before the `Class Declaration` element instead of being put as the `decorators` property's value of the `Class Declaration` element.

Here is an example. Given the following JavaScript code:

```javascript
import {MyDecorator} from './decorators.js';
@MyDecorator
class MyViewModel {
}
```

the output AST is:

```javascript
[
  {
    type: 'ImportDeclaration',
    specifiers: [ [Object] ],
    source: {
      type: 'Literal',
      value: './decorators.js',
      start: 26,
      end: 43,
      range: [Array]
    },
    start: 0,
    end: 44,
    range: [ 0, 44 ]
  },
  [
    {
      type: 'Decorator',
      expression: [Object],
      start: 45,
      end: 57,
      range: [Array]
    }
  ],
  {
    type: 'ClassDeclaration',
    id: {
      type: 'Identifier',
      name: 'MyViewModel',
      start: 64,
      end: 75,
      range: [Array]
    },
    superClass: null,
    decorators: [],
    body: { type: 'ClassBody', body: [], start: 76, end: 79, range: [Array] },
    start: 58,
    end: 79,
    range: [ 58, 79 ]
  }
]
```

As you can see the `ClassDeclaration.decorators` property is an empty array. But just before the `ClassDeclaration` object there is an array of decorators.

Removing the lines

```javascript
    case Token.Decorator:
      return parseDecorators(parser, context) as ESTree.Decorator[];
```

from the `parseModuleItem()` function seems to fix the problem.

**Comment by 3cp** [comment]
Looks like a parsing bug in mode. Turn on module mode triggers the error. Script mode parsing is fine.

```js
parse('@MyDec class A {}', {next: true, module: true});
```

**Comment by 3cp** [comment]
@KFlash any idea why we treated Decorator as a module item, while the spec in the comment didn't mention decorator as a module item?

```js

export function parseModuleItem(
  parser: ParserState,
  context: Context,
  scope: ScopeState | undefined,
  start: number,
  line: number,
  column: number
): any {
  // ecma262/#prod-ModuleItem
  // ModuleItem :
  //    ImportDeclaration
  //    ExportDeclaration
  //    StatementListItem

  switch (parser.token) {
    case Token.ExportKeyword:
      return parseExportDeclaration(parser, context, scope, start, line, column);
    case Token.ImportKeyword:
      return parseImportDeclaration(parser, context, scope, start, line, column);
    case Token.Decorator:
      return parseDecorators(parser, context) as ESTree.Decorator[];
    default:
      return parseStatementListItem(parser, context, scope, Origin.TopLevel, {}, start, line, column);
  }
}
```

**Comment by KFlash** [comment]
As far as I know the decorators was designed after the "old" decorator proposal. They changed it now or going to change it

**Comment by 3cp** [comment]
I see, after I remove the code, following code failed to parse.
```
@bar export default class Foo { }
```

But this is ok:
```
export default @bar class Foo { }
```

Yes, the legacy decorator proposal supports decorate before export keyword, but new proposal (but still not accepted) forces decorator after export keyword.

The decorator spec is kind of a mess, there is a new 3rd proposal going on, because not all parties agree on the 2nd proposal.

But anyway, our support of legacy decorator has the issue highlighted here.
I am not sure about the old estree spec with legacy decorator. Was the spec same as our result? (I can see we got few tests explicitly on this).

**Comment by 3cp** [comment]
There was nothing in estree spec before they added this.

**Comment by 3cp** [comment]
I put the fix to a branch now.

**Comment by 3cp** [comment]
Legacy decorator is very popular, has been used in many front-end frameworks. TypeScript's decorator closely resembles legacy decorator. New decorator proposal is making noise for years, but I have not encountered any real usage.

Babel parser has moved from legacy to latest proposal, but provided two switches, one to turn on legacy decorator syntax, another only to turn on decoratorBeforeExport (as you can see, forcing decorator after export default is quite unpopular).

Since new decorator proposal is going nowhere and legacy decorator is still alive, I suggest we support decorator before and after export regardless. I don't think we need a flag to turn decoratorBeforeExport on and off, because it only causes confusion to end users who are lost in this decorator spec mess.

If this sounds right, I can draft an implementation later next week.

**Comment by KFlash** [comment]
I wonder when the this will move on to Stage 3. Has taken years
