### ISSUE TITLE
Wrong location of `JSXEmptyExpression`

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#125]
```js
require("meriyah").parse('<div>{ }</div>', {loc: true, module: true, jsx: true}).body[0].expression.children[0].expression
{
  type: 'JSXEmptyExpression',
  loc: { start: { line: 1, column: 7 }, end: { line: 1, column: 6 } }
}
```

Should swap `start` and `end`

**Comment by 3cp** [comment]
We tokenised `{ }` as `{` and `[space]}`, the space is not a separate token. So when `parseJSXEmptyExpression()` runs, it didn't move to next token, but tries to finishNode from current position.

@KFlash we probably need to tokenise it as `{`, `[space]` and `}`, otherwise finishNode without nextToken/consume would not work. If don't change tokenisation, I guess we would need some ugly patch.

**Comment by fisker** [comment]
FYI: `'<div>{/* comment*/}</div>'` have same problem

**Comment by 3cp** [comment]
Same cause, comment is not counted as a token in meriyah, but empty space attached to next real token.

**Comment by 3cp** [comment]
Without changing tokenisation, the patch look not too bad.
