### ISSUE TITLE
Bare block statement

### ISSUE THREAD

**Issue by 3cp** [meriyah/meriyah#139]
There is a troublesome change in latest various js implementations.
When a statement starts with `{`, it used to be a block statement.

I am pretty sure that's the case in early 2016. Back then, when you write bare `{a:1}`, it's not an object literal, Chrome (and every other js implementations) thinks is a block statement with one inner statement `1` and it's labelled with `a`, similar with
```js
{
  loop: while(false) {
  }
}
```

Firefox still keeps this old behavior, but nodejs/chome (v8), safari are changed.

|  | {a: 1} | {a:1,b:2} | {a:while(false){}} | 
| :-- | :-- | :--  | :-- |
| chrome/nodejs | object literal | object literal | block statement |
| firefox | block statement | syntax error | block statement |
| safari | object literal | object literal | syntax error |

I am not clear about ECMA spec, it seems following the old behaviour (firefox)??
Many parsers are still using the old behaviour including babel parser. But v8 and safari have moved to a more intuitive behaviour. What should we do here?

Related to #136

**Comment by 3cp** [comment]
To be clear, we are on the old behaviour.

**Comment by KFlash** [comment]
Give me 1 hour to think through this, and I will do an experiment in my private code. 

Do you have a link to the new behaviour in chrome? source? 

In all cases it's super difficult to track and later determined if it's an obj lit or block statement on statement level. That's why all parser use the old behaviour. It was ( and still is I guess ) a issue ticket regarding this on the Acorn repo a few years back where this was discussed. 

If we want to walk down the path of implementing the new behaviour, it require too much I guess. I need to investigate and experiment on it first because it would also require backtracking / lookahead wich Meriyah avoid doing.

Any link to different behaviour would be of help here.

**Comment by 3cp** [comment]
You can just try in chrome/firefox/safari browser console.
I don't have article on this change, just noticed over the years.

**Comment by KFlash** [comment]
I think it's a bug in Chrome? In case {a:1} this is an valid LabelledStatement on statement level. See ECMA specs.
If this followed by for example an assign - = it will become obj lit. In that case you need to reparse from the position of { as an expression and not statement. Thats expensive

**Comment by 3cp** [comment]
> require backtracking / lookahead

This is probably why safari took super simple approach.
The behaviour change is not an issue in practical code, nobody ships code with either bare block statement or bare object literal.

**Comment by 3cp** [comment]
I recall I showed the syntax error for `{a:1,b:2}` in chrome console back in 2016 while `{a:1}` has "no issue", confused the hell out of a group of seasoned programmers. 🤣

**Comment by KFlash** [comment]
Both of your cases are valid statements. I checked webkit source used by Safari. It's also there parsed as statement

**Comment by 3cp** [comment]
I tried in latest safar v14, `{a:while(false){}}` is a syntax error in browser console. Maybe the interactive console runs different code path.

**Comment by KFlash** [comment]
In V8 same https://github.com/v8/v8/blob/master/src/parsing/parser-base.h#L5096

It's a statement

**Comment by 3cp** [comment]
> {a:1} this is an valid LabelledStatement

That's true.
My guess is that chrome could have two parallel parsing branches. But `1` is unlikely (to user) to be a statement, so the branch of object literal got higher score and prevail.

**Comment by KFlash** [comment]
Maybe, but if you want to do this you can - if seen an identifier or `[`, parse it out both as  an expression and statement, and save the result somewhere. Then if valid expression start after parsing out the "BlockStatement", you return that code instead.

`[` is needed, because it could be a computed property name and not start of array literal :)

You could tweak this because you know already what's allowed as part of obj lit - identifier and computed property - and then avoid doing any kind of magic with the rest of token that would lead to an error within an obj lit.

Anyway. I think this is expensive?, but I think this solution is faster than storing the start pos and reparse if an expression.

**Comment by KFlash** [comment]
V8 do eager parsing as 2nd stage and then construct the tree. Maybe you can inherit that method for faster parsing too. Then you shouldn't need to parse out a statement or expression as a whole before doing the eager magic

**Comment by 3cp** [comment]
I am not going to try this hard topic anytime soon :-)

**Comment by KFlash** [comment]
I guess there is a reason why no js parser have implemented it

**Comment by 3cp** [comment]
Bingo! This is a false alarm.

As you checked webkit and v8 source code, it's indeed parsed as statement. I can confirm this with nodejs (not the interactive console).

```
⋊> ~/playground cat > t.js
{a:1,b:2}
⋊> ~/playground node t.js
/Users/huocp/playground/t.js:1
{a:1,b:2}
      ^

SyntaxError: Unexpected token ':'
```

So it's just some special parsing in nodejs/chrome/safari interactive console. I totally understand why they do this in interactive console.

The real js parsers were not changed.
