### ISSUE TITLE
Can meriyah be used as eslint parser?

### ISSUE THREAD

**Issue by kurtextrem** [meriyah/meriyah#158]
Did not find any docu about it, might be a nice use-case?

**Comment by tunnckoCore** [comment]
Yes, I remember. Or I was using `buntis` for a long time. I think both worked, but was using buntis because it can parse TS too.

The whole thing is that you just need to expose `exports.parse` (I think :thinking:) method and point to that file from ESLint config/cli options.

```js
// meriyah-parser.js
const meriyah = require('meriyah');

exports.parse = (source, options) => {
  return meriyah.parseModule(source, options);
}
```

and `--parser ./path/to/meriyah-parser.js`

**Comment by KFlash** [comment]
@tunnckoCore are you still in a urgent need for a fast TS parser? If so, is it ok it doesn't output any AST - only the parsed source stripped for types and annotations and printed back to you with no need for EScodegen and other 3rd party tools?

**Comment by tunnckoCore** [comment]
Not that much. Didn't develop in a very long time.

It sounds good, but it's not very clear to me what you mean. But that's on me, I'm not in dev mode and it may be harder to get without thinking a bit more haha.
