### ISSUE TITLE
Missing some important features

### ISSUE THREAD

**Issue by xuld** [meriyah/meriyah#23]
### 1. Option `{ tolerant: true }`
The parser should smart enough to skip syntax error and continue parsing

### 2. Option `{ skipShebang: true }`
The parser should be able to skip leading `#!`

### 4. The parameter `options` should be optional, rather than adding a `void` type annotation, e.g.

```ts
export declare function parse(source: string, options?: Options): ESTree.Program
```

**Comment by KFlash** [comment]
Hi. You are mixing what is a feature and what's a possible issue with the code itself. I reply on the feature part first.

A tolerant mode as you may know if from other parsers isn't a bullet proof solution. In the future I plan to implement a editor mode to handle such cases. 

When it comes to skipping shebang - the (Hashbang grammar)(https://github.com/tc39/proposal-hashbang) is a Stage 3 proposal. So you can simply enable the `next` option to get this working.

For the rest. I'm in the middle of finishing a v. 1.4 version, and I can export the missing TS types, and look through the ESTree types again.

**Comment by KFlash** [comment]
This should have been solved now, so closing.

**Comment by xuld** [comment]
I don't care about the file size of .d.ts files
For types, maybe directly depends on @types/estree is a good idea

### 7. Include `endIndex` or `endLine/endColumn` in SyntaxError
### 8. Donot prepend [line:column] in SyntaxError.message
In some cases, user will display source locations in their own way(for example: in vscode's error panel), the raw error message is required

p.s Why use `description` instead of standard `message`?
### 9. (maybe)Performance improvement for future ast processing
The ESTree spec defines node.type as a string, which makes the ast more readable, but comparison between strings is more slower than numbers, I'd recommend to add an additional option, if this option is set, all of the node.type properties return a number(actually an enum in typescript)

In one of my use cases, I don't need the Node object except for some node types, allocating objects to store all nodes is wasting time to me, do you have any ideas

**Comment by KFlash** [comment]
With Meriyah I try to follow what's already have been established as a standard among other parsers to be as compatible as possible. The only exception here is Babel's ESTree AST. And the fact web compability isn't enabled by default.

Why not open a PR with some of your suggestions regarding the error code? 

Errors for me until now have had a low-priority because I plan to implement a editor mode and when I do that all nodes will - as you mention - have it's unique enum number plus a incremental uid to all AST nodes. But for now I have had no time to dive into that part of the code.
