### ISSUE TITLE
certain bug: Illegal async arrow function parameter list

### ISSUE THREAD

**Issue by nchanged** [meriyah/meriyah#25]
**version**: 1.4.8
Snippet:
```ts
async function test(){
  const someVar = null;
  const done = async foo => {}
}
```

Throws `Illegal async arrow function parameter list` (also reproducible in the REPL) 

Observations: commenting out `const someVar = null;` fixes the problem.

Can be found in the npm package `electron-updater` right here `node_modules/electron-updater/out/AppUpdater.js`

Related issue: https://github.com/fuse-box/fuse-box/issues/1570

Being parsed without any issues with `typescript` or babel or esprima
https://astexplorer.net/#/gist/3e1e685684c77a841dd4452b677654f9/6e25a2a530fc046e1dc55f5f3285fa7d5acd20d0

**Comment by leeoniya** [comment]
@KFlash have you considered doing something like https://github.com/rust-lang/crater#crater- against large/popular NPM or github repos? i think it would quickly uncover more "edge" cases.

**Comment by nchanged** [comment]
@leeoniya the best way to test it is to run against as many libraries as possible. That I can provide, FuseBox' users started adapting the new version based on meriyah.

**Comment by KFlash** [comment]
@leeoniya I will try to validate against as some libraries soon as I get time. ATM. What @nchanged mentioned is the best solution. 

Beside that I'm stress testing the code entire time, and run 3x different fuzzers and so on. 

**But** to be honest. It's a known issue for me that async and async arrows are troublesome because I'm parsing this in a different way than what the specs says to avoid tons of known issues from other parsers and V8 with async arrow + call expr. This so I can avoid performance bottlenecks.

And sometimes I suddenly find more "edge cases" because one of my previous students did some code changes without knowing what he was doing as what happened with v. 1.4.5.

**Comment by nchanged** [comment]
```
const a = {
  foo: () => {
  },
  bar: async event => {
  }
);
```
This bug hasn't been fixed. Which makes me think there are more similar cases. @KFlash please take a look at all possible variations.

**Comment by KFlash** [comment]
@nchanged Are you sure about this? Btw. Your example is invalid. Missing a right brace.

**Comment by KFlash** [comment]
@nchanged FYI. This bug was caused because of a mutual parser flag and validation against it. This flag  have been replaced with a func arg `assignable` and validations against that arg instead. You can [find it here](https://github.com/meriyah/meriyah/blob/master/src/parser.ts#L7218). This means that this bug will never happen again, and everything related to it can't happen either. So permanently solved :)

**Comment by KFlash** [comment]
@leeoniya @nchanged Parsed a lot of libraries now but couldn't find any issues or "edge cases". 
I added a bunch of new tests just to be sure. Even the [Chinese language](https://github.com/meriyah/meriyah/commit/a33701b5e858a3df5d9473625c62ca11bbf4c639#diff-4b7d31f06c9c0b006d6ac23de5edd1d9R14369-R14387) is very well supported :)
