### ISSUE TITLE
Optimize parsing / simplify

### ISSUE THREAD

**Issue by ghost** [meriyah/meriyah#300]
As of now Meriyha are using multiple functions to parse either script or module and add validation for it 

It should be possible to auto-detect this and reuse same functions 

Here is an example

```ts
flags |= token & Token ModuleStart ? module | strict : None;

// Parse
```

This can be checked in the lexer. If e.g. pos 0,0  to verify, but unnecessary. This only valid on TopLevel except for `import`. 

But start of parse and the first token is one of this. You already know.

Simplest way is just mark `exoirt` and `import` as `ModuleStart` token.

**Comment by 3cp** [comment]
I like the idea.😄

Default to auto detection, unless user explicitly set option module to true or false.

Right now we have pending breaking change, so we can add the one in too for next major release.

**Comment by 3cp** [comment]
The problem is that you can't make a decision on first or first few tokens.

ECMA spec made import/export not runtime statements. In JS runtime, they are statically analysed before running the JS code.

The weird result is the following is perfectly legit JS code.

```js
// use import binding before the import.
console.log(foo);
//...
// import at the end of JS file has same effect as they were imported at the beginning of the JS file.
import foo from "./foo.mjs";
```

The code runs fine in any JS runtime.
