### ISSUE TITLE
Support for older Node.js versions

### ISSUE THREAD

**Issue by mureinik** [meriyah/meriyah#44]
I am looking in using meriyah in a project that needs to support older Node.js versions, specifically from 6 and above.

Looking through the code, the delta doesn't seem to be too great. The restriction of the `engines` entry in `package.json` was added as part of commit 38096e50, and it seems that only the "scaffolding" code under the `scripts` directory really require Node.js 10. The bulk of the code runs perfectly on Node.js 6, as running the tests prooves.

I'd suggest the following:
- Apply the requirement for the `node/no-unsupported-features/es-syntax` rule to support Node.js 10 on the `scripts` directory only (and allow the rest of the code to run on Nodejs 6)
- Run tests on each interesting version in the CI (for argument's sake, the latest of 6, 8, 10 and 12) to ensure this keeps on working.

I have a branch with this work done in my fork (https://github.com/mureinik/meriyah/tree/node-builds), but wanted to raise it to discussion before submitting a PR.

Thoughts and comments are most welcome!

**Comment by KFlash** [comment]
Hi. I can't see any problems in running this on older NodejS versions. The reasons this wasn't supported was because older versions are no longer supported or maintained. And when I developed the parser I thought of using some newer JS syntax that wasn't supported, but you seem to have fixed that. 

I looked at your fork, and your changes looks good to me, so any PR is welcome :-)

**Comment by mureinik** [comment]
Thanks @KFlash!

PR posted: https://github.com/meriyah/meriyah/pull/45
