### ISSUE TITLE
Feature: restrict to given language spec version

### ISSUE THREAD

**Issue by davidbonnet** [meriyah/meriyah#77]
Similar to [Acorn's `ecmaVersion` option](https://github.com/acornjs/acorn/tree/master/acorn#interface), the parser could restrict to a given language spec version (e.g., ES5) and have it throw an error if an unknown token is found (e.g., "Unexpected token `let`" if in ES5 mode).

This could probably be done externally using an `onToken` callback though.

**Comment by KFlash** [comment]
@davidbonnet Is this something you want to make a PR for? For performance reasons I think a `ecmaVersion` should be passed as a func arg. Then you could do `if(esVersion === 12) ....`

**Comment by KFlash** [comment]
Any update on this?

**Comment by davidbonnet** [comment]
Not yet, still planned though.

Is this the right repository to contribute to?

I noticed that you created variants with slightly different functionalities:
- Escaya uses a custom AST instead of the Estree format: https://github.com/escaya/escaya
- Seafox seems similar to Meriyah, but faster: https://github.com/KFlash/seafox
- Buntis parses TypeScript code (its Github repository seems to be private): https://www.npmjs.com/package/buntis

For an Estree-compatible parser, wouldn't it be better to contribute to Seafox?

**Comment by KFlash** [comment]
* Escaya is an totally different world with different code base. It's my own code with no students involved. It does error recovery and incremental parsing as well :)

* Seafox is similar to Meriyah yes, because I tried to figure out what my students "did wrong", and just ignore it.

* Meriyah is the ESTree parser so right choice is to contribute to this repo.
